
2022-11-29 18:46:06,714 C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py changed, reloading.
2022-11-29 18:49:12,012 An error occured while creating a dataframe from api_data | Error: Expected object or value
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 31, in BuildMovAvgChart
    df_raw = pd.read_json(api_data)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 757, in read_json
    return json_reader.read()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 915, in read
    obj = self._get_object_parser(self.data)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 937, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 1064, in parse
    self._parse_no_numpy()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 1321, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
2022-11-29 18:49:12,068 Internal Server Error: /charts/
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 102, in index
    img_chart = getApiEodLimit(conf_chart_radio_form.cleaned_data['mov_av_radio'] , form.cleaned_data['ticker_choice'])
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 169, in getApiEodLimit
    svg_chart = mov_avg.BuildMovAvgChart(raw_data, eod_limit)
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 36, in BuildMovAvgChart
    begin_df_row = df.head(n=1) # parent df head
UnboundLocalError: local variable 'df' referenced before assignment
2022-11-29 18:56:08,877 C:\Training\source\INF601_JKFinalProject\charts\fin_api.py changed, reloading.
2022-11-29 18:56:18,649 An error occured while creating a dataframe from api_data | Error: Expected object or value
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 31, in BuildMovAvgChart
    df_raw = pd.read_json(api_data)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 757, in read_json
    return json_reader.read()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 915, in read
    obj = self._get_object_parser(self.data)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 937, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 1064, in parse
    self._parse_no_numpy()
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 1321, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
2022-11-29 18:56:18,707 Internal Server Error: /charts/
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 102, in index
    img_chart = getApiEodLimit(conf_chart_radio_form.cleaned_data['mov_av_radio'] , form.cleaned_data['ticker_choice'])
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 169, in getApiEodLimit
    svg_chart = mov_avg.BuildMovAvgChart(raw_data, eod_limit)
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 36, in BuildMovAvgChart
    begin_df_row = df.head(n=1) # parent df head
UnboundLocalError: local variable 'df' referenced before assignment
2022-11-29 18:57:01,706 C:\Training\source\INF601_JKFinalProject\charts\fin_api.py changed, reloading.
2022-11-29 18:58:33,073 An error occured while creating a dataframe from api_data | Error: Invalid file path or buffer object type: <class 'list'>
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 31, in BuildMovAvgChart
    df_raw = pd.read_json(api_data)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\json\_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\pandas\io\common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
2022-11-29 18:58:33,136 Internal Server Error: /charts/
Traceback (most recent call last):
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Training\source\INF601_JKFinalProject\djangovenv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 103, in index
    img_chart = getApiEodLimit(conf_chart_radio_form.cleaned_data['mov_av_radio'] , form.cleaned_data['ticker_choice'])
  File "C:\Training\source\INF601_JKFinalProject\charts\views.py", line 171, in getApiEodLimit
    svg_chart = mov_avg.BuildMovAvgChart(raw_data, eod_limit)
  File "C:\Training\source\INF601_JKFinalProject\charts\moving_avg.py", line 36, in BuildMovAvgChart
    begin_df_row = df.head(n=1) # parent df head
UnboundLocalError: local variable 'df' referenced before assignment
2022-11-29 18:59:18,100 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:07:47,977 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:10:30,789 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:12:17,949 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:19:52,567 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:28:40,762 Not Found: /
2022-11-29 19:28:58,282 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 19:54:09,140 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 20:10:38,766 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 20:15:01,460 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
2022-11-29 20:22:18,448 C:\Training\source\INF601_JKFinalProject\charts\views.py changed, reloading.
